### ISSUE TITLE
:bomb: `Bug`: plugin `jenkins-pipeline` panic when Create - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1044]
### What Happened?

- config

```yaml
- name: jenkins-pipeline
  instanceID: default
  dependsOn: []
  options:
    jenkinsURL: http://127.0.0.1:50125
    jenkinsUser: admin
    jenkinsfilePath: https://raw.githubusercontent.com/steinliber/ci-repo/main/springboot/Jenkinsfile
    jenkinsEnableRestart: true
    projectURL: hhttp://127.0.0.1/root/spring-demo
```

- logs

```sh
2022-09-02 10:36:26 ℹ [INFO]  Processing: (jenkins-pipeline/default) -> Create ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1434bfa80]

goroutine 1 [running]:
github.com/devstream-io/devstream/pkg/util/gitlab.(*Client).FileExists(0x14000b30050, {0x13594fcf3, 0xb})
        github.com/devstream-io/devstream/pkg/util/gitlab/file.go:42 +0x1c0
github.com/devstream-io/devstream/pkg/util/gitlab.(*Client).PushLocalFileToRepo(0x14000b30050, 0x140010106f0, 0x1)
        github.com/devstream-io/devstream/pkg/util/gitlab/commit.go:20 +0x328
github.com/devstream-io/devstream/internal/pkg/plugininstaller/ci.PushCIFiles(0x14000c7fef0)
        github.com/devstream-io/devstream/internal/pkg/plugininstaller/ci/installer.go:26 +0x22c
github.com/devstream-io/devstream/internal/pkg/plugininstaller.(*Operator).Execute(0x14001090f48, 0x14000c7fef0)
        github.com/devstream-io/devstream/internal/pkg/plugininstaller/plugininstaller.go:68 +0x238
github.com/devstream-io/devstream/internal/pkg/plugin/jenkinspipeline.Create(0x140012070b0)
        github.com/devstream-io/devstream/internal/pkg/plugin/jenkinspipeline/create.go:26 +0x20c
github.com/devstream-io/devstream/cmd/plugin/jenkins-pipeline.Plugin.Create({0x0, 0x0}, 0x140012070b0)
        github.com/devstream-io/devstream/cmd/plugin/jenkins-pipeline/main.go:16 +0x40
github.com/devstream-io/devstream/internal/pkg/pluginengine.Create(0x14000b586c0)
        github.com/devstream-io/devstream/internal/pkg/pluginengine/plugin.go:26 +0xe4
github.com/devstream-io/devstream/internal/pkg/pluginengine.execute({0x102aa89d8, 0x1400000e6d8}, {0x140001a5308, 0x1, 0x1}, 0x0)
        github.com/devstream-io/devstream/internal/pkg/pluginengine/change.go:136 +0x84c
github.com/devstream-io/devstream/internal/pkg/pluginengine.Apply({0x16fcd3827, 0x26}, 0x0)
        github.com/devstream-io/devstream/internal/pkg/pluginengine/cmd_apply.go:55 +0x5d0
main.applyCMDFunc(0x103ae0d00, {0x14000477420, 0x0, 0x2})
        github.com/devstream-io/devstream/cmd/devstream/apply.go:24 +0x94
github.com/spf13/cobra.(*Command).execute(0x103ae0d00, {0x14000477400, 0x2, 0x2})
        github.com/spf13/cobra@v1.4.0/command.go:860 +0x854
github.com/spf13/cobra.(*Command).ExecuteC(0x103ae0f80)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x6f0
github.com/spf13/cobra.(*Command).Execute(0x103ae0f80)
        github.com/spf13/cobra@v1.4.0/command.go:902 +0x30
main.main()
        github.com/devstream-io/devstream/cmd/devstream/main.go:101 +0x2c
```

### DevStream Version

latest
