### ISSUE TITLE
:bomb: `Bug`: plugin `repo-scaffolding`: options.destinationRepo.owner doesn't work fine

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1045]
### What Happened?

- config

```yaml
- name: repo-scaffolding
  instanceID: springboot
  dependsOn: [ ]
  options:
    destination_repo:
      owner: root
      repo: spring-demo
      branch: master
      repo_type: gitlab
      base_url: http://127.0.0.1
    source_repo:
      owner:  steinliber
      repo: springboot-bootstrap
      repo_type: github
```

note that owner is `root` here, but the real user in GitLab became `Administrator`

![image](https://user-images.githubusercontent.com/18692628/188048871-d4de66e5-fc3b-4917-8942-a360bc10f26c.png)

### DevStream Version

latest
