### ISSUE TITLE
:four_leaf_clover: `Proposal`: `jenkins-pipeline` Options Redesign

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1055]
## What Would You Like to Add? Why Is This Needed?

`jenkins-pipeline` options redesign

## Design

- Old

```yaml
tools:
- name: jenkins-pipeline
  instanceID: default
  dependsOn: []
  options:
    jenkinsURL: http://54.71.232.26:32000
    jenkinsUser: admin
    jenkinsfilePath: https://xxx/Jenkinsfile
    jenkinsEnableRestart: true
    projectURL: http://54.71.232.26:30080/root/spring-demo
    jenkinsNamespace: jenkins
    harborURL: http://harbor.example.com:80
    harborUser: admin
```

- New

```yaml
tools:
- name: jenkins-pipeline
  instanceID: default
  dependsOn: []
  options:
    jenkins:
      url: http://54.71.232.26:32000/
      user: admin
      namespace: jenkins
      enableRestart: true
    scm:
      projectURL: http://54.71.232.26:30080/root/spring-demo
      projectBranch: master
    pipeline:
      jobName: jobs/test-job
      jenkinsfilePath: https://xxx/Jenkinsfile
      imageRepo:
        url: http://harbor.example.com:80
        user: admin
```
