### ISSUE TITLE
:four_leaf_clover: `Proposal`: jenkins-pipeline better config options

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#1102]
## What Would You Like to Add? Why Is This Needed?
current `Jenkins` scm config is like below 
```yaml
scm:
  projectURL: http://IPADDRESS:30080/root/spring-demo
  projectBranch: master
```

If we want to support clone git repo by ssh, config will like below
```yaml
scm:
  projectURL: git@IPADDRESS:30022:root/spring-demo.git
  projectBranch: master
```
but in this config, we can't get `Gitlab` API Address, So we can't create webhook by gitlab api.

## Design
what about extract these config from projectURL
```yaml
scm:
  host: IPADDRESS
  hostHTTPPort: 30080
  hostSSHPort: 30022
  projectPath: root/spring-demo
  projectBranch: master
```

**Comment by daniel-hutao** [comment]
How about we change it to:

```yaml
scm:
  hostIP: 192.168.100.100
  HTTPPort: 30080
  SSHPort: 30022
  user: root
  project: spring-demo
  branch: master
```
