### ISSUE TITLE
:four_leaf_clover: `Proposal`: Add New Command `dtm install argocd`

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1204]
## What Would You Like to Add? Why Is This Needed?

Now we have the `helm-installer` that can install a Helm Chart with a minimum config file like:

```yaml
---
varFile: ""
toolFile: ""
pluginDir: ""
state:
  backend: local
  options:
    stateFile: devstream.state

---
tools:
- name: helm-installer
  instanceID: argocd-001
```

The only config item users told us here is "argocd-001". Everything else is actually configured by default. So we can completely simplify this configuration file even further.

## Design

New command: 

- `dtm install TOOL_NAME`
- `dtm uninstall TOOL_NAME`

## Anything else

Perhaps later we can further add this command:

- `dtm install TOOL_NAME -f ./values.yaml`

That will generate config like below:

```yaml
---
varFile: ""
toolFile: ""
pluginDir: ""
state:
  backend: local
  options:
    stateFile: devstream.state

---
tools:
- name: helm-installer
  instanceID: TOOL_NAME-001
  dependsOn: []
  options:
    valuesYaml: "./values.yaml"
```
