### ISSUE TITLE
:four_leaf_clover: `Proposal`: gitlab-ci general plugins

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#1215]
## What Would You Like to Add? Why Is This Needed?
we should add a plugin for `gitlab-ci` with a more generic function. we have `java`, `python`, `nodejs` for now, But their design is too simple. We can create a new `gitlab-ci` plugin for more generic usage.

## Design
- support sonarqube
- support multi language
- support image repo
- support notify (dingding)
- support gitlab-runner

## Anything else
- example config
```
tools:
- name: gitlab-ci
  instanceID: default
  dependsOn: [ ]
  options:
    scm:
      cloneURL: git@gitlab.com/test/test-exmaple.git
      branch: YOUR_PROJECT_BRANCH
    ci:
      configLocation: git@github.com:devstream-io/devstream.git//.github/workflows
      imageRepo:
        url: http://harbor.example.com:80
        user: admin
      dingTalk:
        name: YOUR_DINGTALK_ROBOT_NAME
        webhook: https://oapi.dingtalk.com/robot/send?access_token=changemeByConfig
        securityType: YOUR_DINGTALK_SECRET_TYPE
        securityValue: YOUR_DINGTALK_SECRET_VALUE
      sonarqube:
        url: http://sonar.example.com
        token: YOUR_SONAR_TOKEN
        name: sonar_test
```
