### ISSUE TITLE
:four_leaf_clover: `Proposal`: Config File Format Refactoring

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#1251]
## What Would You Like to Add? Why Is This Needed?

The current configuration file already has some complexity, we can try to make some improvements.

### Single Config File

Usage: `dtm apply -f config.yaml`

- config.yaml

```yaml
config:
  state:
    backend: k8s # local, s3 or k8s
    options:
      namespace: devstream # optional, default is "devstream", will be created if not exists
      configmap: state # optional, default is "state", will be created if not exists

vars:
  foo: bar

tools:
- name: jenkins
  instanceID: default
  dependsOn: [ ]
  options:
    foo: [[ foo ]]

apps:
- name: service-A
  spec:
    language: python
    framework: django

pipelineTemplates:
- name: ci-pipeline-1
  type: githubactions # 对应一个插件
  options:
    foo: bar
```

### Config Directory

Usage: `dtm apply -f .` or `dtm apply -f /tmp/.devstream/aaa`

Users can specify a directory as the "config directory", and all yaml files in the specified directory will be treated as config files, and these config files will be merged.

e.g.

There are 5 yaml files in the current directory, the contents can be:

- config.yaml

```yaml
config:
  state:
    backend: k8s # local, s3 or k8s
    options:
      namespace: devstream # optional, default is "devstream", will be created if not exists
      configmap: state # optional, default is "state", will be created if not exists
```

- variables.yaml

```yaml
vars:
  foo: bar
```

- tools.yaml

```yaml
tools:
- name: jenkins
  instanceID: default
  dependsOn: [ ]
  options:
    foo: [[ foo ]]
```

- apps.yaml

```yaml
apps:
- name: service-A
  spec:
    language: python
    framework: django

pipelineTemplates:
- name: ci-pipeline-1
  type: githubactions # 对应一个插件
  options:
    foo: bar
```

The name of the files are not important, as long as they contain the keys apps, tools, config etc. dtm will recognize the contents of the files and merge them.
