### ISSUE TITLE
:four_leaf_clover: `Proposal`: CI: yaml lint

### ISSUE THREAD

**Issue by aFlyBird0** [devstream-io/devstream#1285]
## What Would You Like to Add? Why Is This Needed?

We need lint YAML files in dtm. There are many things to lint, such as:

e.g.

```yaml
# OK:
key:
- value1
- value2
# NOT OK:
key:
   - value1
   - value2
```

And we can create a workflow to check them automatically.
