### ISSUE TITLE
:four_leaf_clover: `Proposal`: jira/zentao/trello use new repo options

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#1336]
## What Would You Like to Add? Why Is This Needed?
Since we have Jira/ZenTao/Trello plugin, which is used to manage the app(or project). I think we can add a new option `lifecycleManagement` for  the app config, just like the config below. 

```yaml
config:
  state: # state config, backend can be local, s3 or k8s
    backend: local
    options:
      stateFile: devstream.state

vars:
  repoOwner: steinliber
  imageRepoOwner: steinsliber

apps:
- name: dtm-e2e-go
  spec:
    framework: gin
    language: golang
  repo:
    owner: [[ repoOwner ]]
    scmType: github
  repoTemplate:
    url: github.com/devstream-io/dtm-repo-scaffolding-golang-gin
  ci:
  - type: github-actions
    options:
      imageRepo:
        user: [[ imageRepoOwner ]]
  lifecycleManagement: # here is lifecycleManagement config
    type: jira-integ
    options:
      baseUrl: https://steinliber.atlassian.net
      projectKey: TEST
      userEmail: steinliber@gmail.com
```

## Design
With the previous configuration， we can get the following benefits:
- since the app depends on tools, we can't create `jira-github-integ` tool with the app, because  this app repo is not created before `jira-github-integ` tool runs.
- with this config, we can use like [jenkins-jira-plugin](https://plugins.jenkins.io/jira/) to integrate all app's related info into Jira.
- `lifecycleManagement` is also a property of the app, what we want to do is to configure every aspect of the application lifecycle, put `lifecycleManagement` in the app will make config easier.

## Anything else
Maybe we can change `lifecycleManagement` to a  more understandable option so that users can know what this config does more easily.
