### ISSUE TITLE
Proposal: remove the `tools[n].name` field in config.yaml

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#431]
## Description

I think the `name` field is meaningless. See what we used as a name in config file now:

- `config.yaml`
```yaml
tools:
- name: go-webapp-repo
  plugin: github-repo-scaffolding-golang
  options:
    owner: [[ githubUsername ]]
    org: ""
    repo: [[ repoName ]]
    branch: [[ defaultBranch ]]
    image_repo: [[ dockerhubUsername ]]/[[ repoName ]]
- name: jira-github-default
  plugin: jira-github-integ
  dependsOn: [ "go-webapp-repo.github-repo-scaffolding-golang" ]
  options:
    owner: [[ githubUsername ]]
    repo: [[ repoName ]]
    jiraBaseUrl: https://[[ jiraID ]].atlassian.net
    jiraUserEmail: [[ jiraUserEmail ]]
    jiraProjectKey: [[ jiraProjectKey ]]
    branch: main
```

The `name` configuration will not affect the deployment result of the tool at all. Its only function is to be used as part of the key in the state, thereby supporting multiple instances.

Why don't we randomly generate an instance name to support multiple instances? This way the user doesn't need to think: what should I name it? Then they begin to wonder: what is the usage of my name?

And the existence of this `name` is not conducive to our interpretation of the `plugin` field, we call it `plugin name`? What about `name` field, maybe you need to call it: `instance name`, but I believe that many people will call it: `plugin name` too. So confusing.

---

## Design

- delete "name", add "instance", but the "instance" can be left blank. If users don't need multi-instance support, they can ignore the instance configuration.

```yaml
tools:
- plugin: github-repo-scaffolding-golang
  instance: "" # Can be left blank, dtm will automatically fill in random strings.
  dependsOn: []
  options:
    foo1: bar1
- plugin: github-repo-scaffolding-golang
  instance: "" # Can be left blank, dtm will automatically fill in random strings.
  dependsOn: []
  options:
    foo2: bar2
- plugin: jira-github-integ
  instance: "test"
  dependsOn: []
  options:
    foo2: bar2
- plugin: jira-github-integ
  instance: "prod"
  dependsOn: []
  options:
    foo2: bar2
```

**Comment by daniel-hutao** [comment]
```yaml
tools:
- instance: "test"
  plugin: jira-github-integ
  dependsOn: []
  options:
    foo2: bar2
- instance: "prod"
  plugin: jira-github-integ
  dependsOn: []
  options:
    foo2: bar2
```

**Comment by daniel-hutao** [comment]
```yaml
tools:
- plugin: jira-github-integ
  - instance: "test"
    dependsOn: []
    options:
      foo2: bar2
  - instance: "prod"
    plugin: jira-github-integ
    dependsOn: []
    options:
      foo2: bar2
```

vs

```yaml
tools:
- name: jira-github-integ
  instanceID: "test"
  dependsOn: []
  options:
    foo1: bar1
- name: github-repo-scaffolding-golang
  instanceID: "test"
  dependsOn: []
  options:
    foo1: bar1
```

**Comment by daniel-hutao** [comment]
final version:

```yaml
tools:
- name: jira-github-integ
  instanceID: "test"
  dependsOn: []
  options:
    foo1: bar1
- name: github-repo-scaffolding-golang
  instanceID: "prod"
  dependsOn: []
  options:
    foo1: bar1
```

/assign @daniel-hutao

**Comment by daniel-hutao** [comment]
final version:

```yaml
tools:
- name: jira-github-integ
  instanceID: "test"
  dependsOn: []
  options:
    foo1: bar1
- name: github-repo-scaffolding-golang
  instanceID: "prod"
  dependsOn: []
  options:
    foo1: bar1
```

/assign @daniel-hutao
