### ISSUE TITLE
Bug(githubactions-golang): GitHub Actions workflow failed with error: `Error: Username and password required`

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#434]
## Describe the Bug

Test case: GitOps

1. `dtm apply xxx` succeeded with NO error
2. GitHub Actions workflow failed:

![image](https://user-images.githubusercontent.com/18692628/164889224-63be0602-5353-4a27-a7f2-55847857da2c.png)

/plugin githubactions-golang
/assign @daniel-hutao

**Comment by daniel-hutao** [comment]
There is another point to consider. Currently, `DockerHub Username` doesn't support passing through configuration files, but uses environment variables, which is unreasonable. I think it can be changed like this:

```yaml
docker:
  enable: True
  registry:
    type: dockerhub/harbor
    username: NAME
    repository: REPO
```

/cc @devstream-io/pmc
