### ISSUE TITLE
Proposal: command `dtm show config` with no flag to print main config sample

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#468]
## Description

We can now use the command `dtm show config --plugin=A-PLUGIN-NAME` print a sample config with one plugin/tool. But how to write the main config file: `config.yaml`?

## Design

- `dtm show config` print the text like below:

\# config.yaml sample:
```yaml
varFile: variables.yaml
toolFile: tools.yaml
state:
  backend: local
  options:
    stateFile: devstream.state
```

\# tools.yaml sample:
```yaml
tools:
- name: github-repo-scaffolding-golang
  instanceID: default
  options:
    owner: [[ githubUsername ]]
    org: ""
    repo: [[ repoName ]]
```

\# variables.yaml sample:
```yaml
githubUsername: daniel-hutao
repo: go-webapp-demo
```

@IronCore864 Are there some suggestions?
