### ISSUE TITLE
:four_leaf_clover: `Proposal`: Plugin `githubactions-golang` Enhancement (sub-task with #513)

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#517]
### What would you like to add? Why is this needed?

See #513 for the details

**Comment by IronCore864** [comment]
```yaml
tools:
- name: githubactions-golang
  instanceID: default
  dependsOn: []
  options:
    owner: YOUR_GITHUB_USERNAME
    org: YOUR_ORGANIZATION_NAME
    repo: YOUR_REPO_NAME
    language:
      name: go
      version: "1.17"
    branch: main
    build:
      enable: True
      command: "go build ./..."
    test:
      enable: True
      command: "go test ./..."
      coverage:
        enable: False
        profile: "-race -covermode=atomic"
        output: "coverage.out"
    docker:
      enable: True
      registry:
        type: dockerhub
        username: YOUR_DOCKERHUB_USERNAME
        repository: YOUR_DOCKERHUB_REPOSITORY
```

Same issue regarding the owner/org issue. See https://github.com/devstream-io/devstream/issues/516#issuecomment-1136999392 for more info.

Besides, we need a better usage example, with better docs explaining each param in detail. I.E., if it's mandatory, what it does, what it means, and the default values. Maybe provide a minimum config that could work as well.

## Be Brave, Be Imaginative

Anything that isn't following the clean code best practice, refactor it.

Any feature you think would add value to end-users, add it.

Any configuration refactors / documentation updates that would improve the end users' quality of life, do it.

Be brave when deleting unnecessary code, and be imaginative when adding new features.
