### ISSUE TITLE
:four_leaf_clover: `Proposal`: Plugin `githubactions-python` Enhancement (sub-task of #513)

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#519]
### What would you like to add? Why is this needed?

See #513 for the details

**Comment by daniel-hutao** [comment]
@lyleshaw Go ahead and happy coding!
@IronCore864 is very good at py, on the contrary I am not very good at it. So he will communicate with you more about this issue later.

/assign @lyleshaw

**Comment by IronCore864** [comment]
# githubactions-python Plugin Improvements

## Config Improvement

The current config for this plugin is like the following:

```yaml
tools:
- name: githubactions-python
  instanceID: default
  options:
    owner: YOUR_GITHUB_USERNAME
    org: YOUR_ORGANIZATION_NAME
    repo: YOUR_REPO_NAME
    language:
      name: python
      version: "3.8"
    branch: main
```

It seems the `language.name` is redundant since this plugin will only handle GitHub actions workflows for Python. This can be removed.

## New Features

Refer to https://github.com/actions/setup-python and https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python for possible new features.

Examples:

- exclude a specific Python version
- support both pip and pipenv
- cache pip dependencies
- cache pipenv dependencies
- matrix testing
- install dependencies
- requirements files (pip)
- test the code (pytest)
- test coverage (pytest-cov)
- lint (flake8)
- run tests with tox (https://tox.wiki/en/latest/)

There is no need to implement every single one of them; use your experience and best judgement to decide which features to include first.
