### ISSUE TITLE
:four_leaf_clover: `Proposal`: `dtm show config` Enhancement to Support Print Core Config

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#556]
### What would you like to add? Why is this needed?

We have a command to print the config with any specified plugin:

```sh
dtm show config --plugin=A-PLUGIN-NAME
```

But how to tell users that how to write `core config`? Maybe we can use the command

```sh
dtm show config
```

without `--plugin` to print the `core config`:

```yaml
# var file path, you can set it to absolute path or relative path.
varFile: variables-sample.yaml
# tool file path, you can set it to absolute path or relative path.
toolFile: tools-sample.yaml
# state config, backend can be local or s3
state:
  backend: local
  options:
    stateFile: devstream.state
```

And tell users: If you want to print the config template with a specified plugin, please use the command `dtm show config --plugin=A-PLUGIN-NAME`
