### ISSUE TITLE
:four_leaf_clover: `Proposal`: Add a plugin to create a Jenkins pipeline

### ISSUE THREAD

**Issue by prodanlabs** [devstream-io/devstream#582]
## Design
```yaml
toolFile: config.yaml
tools:
  - name: jenkins-pipeline
    instanceID: demo-apply
    options:
      git:
        url: "https://github.com/prodanlabs/tekton-examples.git"
        branch: "main"
      mode: kubernetes
      jenkins:
        url: "http://124.71.14.222:31765"
        username: admin
        apitoken: oiio
        credential:
          id: "test"
          user: "admin"
          passwd: "xxxx"
          policy: IfNotExistCreate
      job:
        name: devstream-auto
      pipeline: |
        pod:
        - containertemplate:
            name: jnlp
            image: jenkins/inbound-agent:latest-alpine
        - containertemplate:
            name: golang
            image: "golang:alpine3.15",
            command: "sleep",
            args: "600s",
            envVars: |
            - key: 'CGO_ENABLED'
              value: '0'
        stages:
        -  stage:
             name: "Git Clone"
        -  stage:
             name: "Golang Test"
             script: |
               cd ${WORKSPACE}/
               go version
               go test

state:
  backend: local
  options:
    stateFile: devstream.state
```

```
prodan@ubuntu:/opt/workspaces/devstream$ ./dtm apply -y
2022-05-22 21:23:01 ℹ [INFO]  Apply started.
2022-05-22 21:23:01 ℹ [INFO]  { config.yaml 0xc0001c7310}
2022-05-22 21:23:01 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-05-22 21:23:01 ℹ [INFO]  Using local backend. State file: devstream.state.
2022-05-22 21:23:01 ℹ [INFO]  Tool (jenkins-pipeline/demo-apply) found in config but doesn't exist in the state, will be created.
2022-05-22 21:23:01 ℹ [INFO]  Start executing the plan.
2022-05-22 21:23:01 ℹ [INFO]  Changes count: 1.
2022-05-22 21:23:01 ℹ [INFO]  -------------------- [  Processing progress: 1/1.  ] --------------------
2022-05-22 21:23:01 ℹ [INFO]  Processing: (jenkins-pipeline/demo-apply) -> Create ...
2022-05-22 21:23:01 ℹ [INFO]  jenkins version: 2.332.3
2022-05-22 21:23:01 ℹ [INFO]  plugin: kubernetes version: 3580.v78271e5631dc
2022-05-22 21:23:01 ✔ [SUCCESS]  Tool (jenkins-pipeline/demo-apply) Create done.
2022-05-22 21:23:01 ℹ [INFO]  -------------------- [  Processing done.  ] --------------------
2022-05-22 21:23:01 ✔ [SUCCESS]  All plugins applied successfully.
2022-05-22 21:23:01 ✔ [SUCCESS]  Apply finished.
```
![image](https://user-images.githubusercontent.com/28917392/169697386-c9a64237-41f2-49dd-980e-12d2d2ae874e.png)

![image](https://user-images.githubusercontent.com/28917392/169697537-35bbf227-55ab-4b0e-891f-c9057be4df98.png)

![image](https://user-images.githubusercontent.com/28917392/169697644-02f8d1ae-3378-4527-b9f1-e0ac37a19906.png)

```
kubectl get po -n jenkins 
NAME                               READY   STATUS    RESTARTS   AGE
jenkins-master-0                   1/1     Running   1          3d1h
jenkins-slave-alpine-m14c4-tgghn   2/2     Running   0          12s
```

### question
1. There are many Jenkins operating environments, some running on kubernetes, docker or bare metal, and there are differences in configuration. A plan may be needed to implement it gradually.
2. I looked at the third-party libraries related to Jenkins, and it seems that they are not active anymore. I don't know if devstream has requirements for third-party libraries. 
Generally speaking, large open source projects will not use inactive third-party libraries. I spent an hour implementing a simple Jenkins REST client，like this:
```go
type PipelineInterface interface {
	Create(ctx context.Context, name string, body interface{}) error
	Update(ctx context.Context, name string, body interface{}) error
	Delete(ctx context.Context, name string) error
	Get(ctx context.Context, name string) error
	List(ctx context.Context) error
}
```

What do you think about this plugin? This plugin is still a demo :)

**Comment by daniel-hutao** [comment]
@prodanlabs Thank you very much for the proposal and there is a great demo screenshot. For this plugin, maybe we need more detailed design before we can start development. For example, the password/token fields in the configuration file may not be suitable to save directly in plain text.

Also as you mentioned, jenkins can interface with docker, k8s, vm and many more, so which one should we implement first? Does one plugin support all of them?

Also we already have a `jenkins` plugin, so maybe there is some generic base configuration that can be added to the `jenkins` plugin. Perhaps you might consider looking at the `jenkins` plugin implementation first to see if there are enhancement points you can implement.

For pipeline, I think it's a good idea to start with the `k8s` way. Maybe it's a new plugin, I'm not sure if it should be called `jenkins-pipeline` or `jenkins-k8s-pipeline` or something else; look forward to more input @devstream-io/devstream!

**Comment by prodanlabs** [comment]
1. password/token security.
The passwords of git and docker registry can be added by users themselves on Jenkins, and the credential ID is passed in config.yaml.
Jenkins `API Token` can be encrypted with some encryption algorithm.

2. The current jenkins plugin seems to just install the plugin. In addition, as far as I know, the way Jenkins integrates with kubernetes is implemented through the kubernetes plugin, not through kubernetes crd and other methods. Therefore, creating Jenkins resource objects can only be done through jenkins `REST API`.

3. I personally prefer `jenkins-k8s-pipeline`, `jenkins-docker-pipeline`, etc.

To be honest, in  `kubernetes` , a general helm plugin can basically solve the problem of software installation, `devstream` should solve the complex problems of DevOps applications, such as simplifying the configuration, rather than doing too much work in installing DevOps applications, I Personally think so.

**Comment by prodanlabs** [comment]
Hi @daniel-hutao  do you have any suggestions?

```yaml
toolFile: config.yaml
tools:
- name: jenkins-k8s-pipeline
  instanceID: demo
  options:
    git:
      url: "https://github.com/prodanlabs/tekton-examples.git"
      branch: "main"
      credentialID: "1111" # Jenkins credential id
    jenkinsURL: "http://124.71.14.222:31765"
    jobName: devstream-auto
    pod: # kubernetes pod template
      label: "test" 
      container:
      - name: "jnlp"
        image: "jenkins/inbound-agent:latest-alpine"
      - name: "golang"
        image: "golang:alpine3.15"
        command: 
        - sleep
        args: 
        - 600s
        Env:
        - key: 'CGO_ENABLED'
          value: '0'
        - key: 'CGO_ENABLED_EE'
          value: '0'
      volumes:
        emptyDirVolume:
        - mountPath: "/tmp"
        - mountPath: "/tmp22"
        secretVolume:
        - mountPath: "/test"
          secretName: "test"
        - mountPath: "/test2"
          secretName: "test2"
    pipeline: # Jenkins Pipeline template
      environment:
      - key: 'PPPP'
        value: '22'
      stages:
      - name: "Git Clone"
        container: "jnlp"
        gitClone: true
      - name: "Go Test"
        container: "golang"
        script: |-
          cd ${WORKSPACE}/
          go version
          go test
state:
  backend: local
  options:
    stateFile: devstream.state
```
