### ISSUE TITLE
:four_leaf_clover: `Proposal`: dtm Configuration Enhancement: Single Profile Support

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#596]
## What Would You Like to Add? Why is This Needed?

Currently we need up to 3 config files:
- config.yaml
- variables.yaml
- tools.yaml

This has a certain understanding cost for new users to get started. So I think it's necessary to support the integration of the 3 config files together to make it easier for new users to get started with `dtm`

## Design

- old `config.yaml`

```yaml
varFile: variables.yaml
toolFile: tools.yaml
state:
  backend: local
  options:
    stateFile: devstream.state
```

- old `variables.yaml`

```yaml
foo: bar
```

- old `tools.yaml`

```yaml
tools:
- name: A-PLUGIN-NAME
  instanceID: default
  options:
    foo: bar
```

---

- new `config.yaml`

```yaml
---
# core config (please don't change this comment)
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state:
  backend: local
  options:
    stateFile: devstream.state

---
# variables config (please don't change this comment)
foo: bar

---
# plugins config (please don't change this comment)
tools:
- name: A-PLUGIN-NAME
  instanceID: default
  options:
    foo: bar
```
