### ISSUE TITLE
:four_leaf_clover: `Proposal`: Add More `ut` to the `configloader` Package

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#661]
## What Would You Like to Add? Why Is This Needed?

We have a function named LoadConfig() in `internal/pkg/configloader/config.go:29`. This is the entry logic of the `configloader` package. I'd like to add some `ut` to this function.

**ut samples**: internal/pkg/configloader/configloader_test.go
**config file format ref**: examples/gitops.yaml

Please check [gingko's documentation](https://onsi.github.io/ginkgo/) before you start writing ut.

## Design

Maybe you can generate some correct wrong configuration files, write them to disk, and then go use them in ut; finally remember to clean up any temporary files generated.

## Anything else

About how to test the config logic locally, see #655 for more details.

Take the first step, go for it! Feel free to contact me if you have any difficulties.

**Comment by DunyuSong** [comment]
I want to do it.

**Comment by daniel-hutao** [comment]
@DunyuSong Go for it, happy coding!

**Comment by aFlyBird0** [comment]
Feel free to ask me for any help. Development is not urgent, just take your time at your pace. @DunyuSong

**Comment by aFlyBird0** [comment]
For this issue we can start by keeping it simple, i.e. testing only the `LoadConfig` function without testing the three small functions inside it.

You can construct different function inputs (the correct config file can be found in #655, or you can construct some incorrect config file) and then determine if the output of `LoadConfig` is as expected (return the correct `*Config`, or return an error when the config file is incorrect).

@DunyuSong

**Comment by aFlyBird0** [comment]
More precisely, for each test case, you can create a string that contains configuration information, such as :
```
---
# tool file path, you can set it to absolute path or relative path.
toolFile: "" # here is a relative path.
# state config, backend can be local or s3
state:
  backend: local
  options:
    stateFile: devstream.state

---
tools:
  - name: github-repo-scaffolding-golang
    instanceID: default
    options:
      owner: daniel-hutao
      repo: go-webapp-devstream-demo
      branch: main
      image_repo: exploitht/go-webapp-devstream-demo
  - name: githubactions-golang
    instanceID: default
    dependsOn: ["github-repo-scaffolding-golang.default"]
    options:
      owner: daniel-hutao
      repo: go-webapp-devstream-demo
      language:
        name: go
        version: "1.17"
      branch: main
      build:
        enable: True
      test:
        enable: True
        coverage:
          enable: True
      docker:
        enable: False
```
Then write this string (configuration content details), to a specific file, such as ``quickstart.yaml``.

Then call the `LoadConfig("quickstart.yaml")` method and determine if the `*Config, error` returned by the function is responsible for the expectation.

After that, test the other types of configuration examples in #655 in the same way.
