### ISSUE TITLE
:four_leaf_clover: `Proposal`: argo Support kustomize

### ISSUE THREAD

**Issue by huang12zheng** [devstream-io/devstream#675]
## What Would You Like to Add? Why Is This Needed?

* dtm only supports Helm repo.
Here's what I found:
https://github.com/devstream-io/devstream/blob/main/internal/pkg/plugin/argocdapp/argocdapp.go#L49-L53
```go
res["src"] = map[string]interface{}{
		"repoURL":   opts.Source.RepoURL,
		"path":      opts.Source.Path,
		"valueFile": opts.Source.Valuefile,
	}
```

* We can find in the Argo documentation:
https://argo-cd.readthedocs.io/en/stable/user-guide/helm/
https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook-kustomize

    kustomize:
      version: v3.5.4
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal
```

Maybe there's something I don't know, or maybe this isn't a good time to support this

## Design
none

## Anything else

none
