### ISSUE TITLE
:bomb: `Bug`: dtm init failed in version 0.6.1

### ISSUE THREAD

**Issue by zhujinhe** [devstream-io/devstream#695]
### What Happened?

I'm following the tutorial `https://docs.devstream.io/en/latest/quickstart/` step by step.
and failed in step 3: dtm init -f quickstart.yaml
here is the error message:

```
# dtm init -f quickstart.yaml
2022-06-20 12:29:21 ✖ [ERROR]  Config file validation failed: tool file is empty.
2022-06-20 12:29:21 ℹ [INFO]  Using dir <.devstream> to store plugins.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e8537]

goroutine 1 [running]:
github.com/devstream-io/devstream/internal/pkg/pluginmanager.DownloadPlugins(0x0)
	github.com/devstream-io/devstream/internal/pkg/pluginmanager/manager.go:30 +0x177
main.initCMDFunc(0x18a8a80, {0xc000045cc0, 0x0, 0x2})
	github.com/devstream-io/devstream/cmd/devstream/init.go:26 +0x185
github.com/spf13/cobra.(*Command).execute(0x18a8a80, {0xc000045ca0, 0x2, 0x2})
	github.com/spf13/cobra@v1.4.0/command.go:860 +0xb67
github.com/spf13/cobra.(*Command).ExecuteC(0x18a9200)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x8b3
github.com/spf13/cobra.(*Command).Execute(0x18a9200)
	github.com/spf13/cobra@v1.4.0/command.go:902 +0x2f
main.main()
	github.com/devstream-io/devstream/cmd/devstream/main.go:98 +0x32
```

It seems that setting toolFile to "" was not allowed in version 0.6.1.
https://github.com/devstream-io/devstream/blob/adf3dffa19d2450a367f998717a1a11c5e842cc8/internal/pkg/configloader/validation.go#L85-L87

### Anything else

dtm version
```0.6.1```

Nothing changed in  quickstart.yaml except the YOUR_GITHUB_USERNAME_CASE_SENSITIVE and YOUR_DOCKER_USERNAME by the tutorial:
```
---
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state

---
# plugins config
tools:
  - name: github-repo-scaffolding-golang
    instanceID: default
    options:
      owner: zhujinhe
      repo: go-webapp-devstream-demo
      branch: main
      image_repo: zhujinhe/go-webapp-devstream-demo
  - name: githubactions-golang
    instanceID: default
    dependsOn: ["github-repo-scaffolding-golang.default"]
    options:
      owner: zhujinhe
      repo: go-webapp-devstream-demo
      language:
        name: go
        version: "1.17"
      branch: main
      build:
        enable: True
      test:
        enable: True
        coverage:
          enable: True
      docker:
        enable: False
```

### DevStream Version

latest
