### ISSUE TITLE
:bomb: `Bug`:  use `kube-prometheus` plugin seem happend error

### ISSUE THREAD

**Issue by NUCsimple** [devstream-io/devstream#834]
### What Happened?

prom.yaml:
```
---
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state

---
# plugins config
tools:
  - name: kube-prometheus
    options:
      create_namespace: true
      repo:
        name: bitnami
        url: https://charts.bitnami.com/bitnami
      chart:
        namespace: monitoring
        timeout: "30s"
        chart_name: kube-prometheus
```

How to use:

`dtm apply -f examples/prom.yaml`

What happend:

2022-07-11 22:47:34 !! [ERROR]  Errors Map: key(kube-prometheus/-Create) -> value(non-absolute URLs should be in form of repo_name/path_to_chart, got: kube-prometheus)
2022-07-11 22:47:34 !! [ERROR]  Apply failed => some error(s) occurred during plugins apply process.

### DevStream Version

latest
