### ISSUE TITLE
:four_leaf_clover: `Proposal`: New basic type in devstream

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#849]
## What Would You Like to Add? Why Is This Needed?
We use the `plugin` to describe all basic unit in `devstrem` for now, for example `trello`, `trellogithub` and `jiragithub`. In my option, they basically are not the same. The plugin like `trello` means we want to create this service in some environment like `k8s` or `docker`, `trellogithub` and `trellogithub` is used to connect different service, which means Their implementation depends primarily on request API for service， maybe separate these different type is a good option.
 
## Design
Add a new basic type `connector` for service(like `github`, `trello`, or `jira`), the config like below 
```yaml
---
# plugins config
tools:
  - name: github-repo-scaffolding-golang
    instanceID: default
    options:
      owner: [[ githubUsername ]]
      org: ""
      repo: [[ repoName ]]
      branch: [[ defaultBranch ]]
      image_repo: [[ dockerhubUsername ]]/[[ repoName ]]
---
# connector config
connector:
  - name: jira-github-integ
    instanceID: default
    dependsOn: [ "github-repo-scaffolding-golang.default" ]
    options:
      jira:
          BaseUrl: https://[[ jiraID ]].atlassian.net
          jiraUserEmail: [[ jiraUserEmail ]]
          jiraUserEmail: [[ jiraUserEmail ]]
          jiraProjectKey: [[ jiraProjectKey ]]
     github:
          owner: [[ githubUsername ]]
          repo: [[ repoName ]]
          branch: main
```
