### ISSUE TITLE
:open_book: `Docs`: The Full Configuration Examples Need to be Added to the Plugin Documentations

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#941]
### What should be changed?

A long time ago, we had only one configuration file, in a format that probably looked like below:

```yaml
tools:
  foo: bar
```

So at that time, the configuration examples given in our plugin documentations are the same as above.

But now the configuration file has been split into 3 parts: `core config`, `var config` and `tools config`. So when a user opens one of our plugin documents and sees the example like below, he won't know how to `apply` it.

![image](https://user-images.githubusercontent.com/18692628/182821641-8190e9fc-6be4-4eb4-9e1b-2f90c86a62d7.png)

I think all the plugin documentations about the configuration examples should be changed to like below:

```yaml
---
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state

---
# variables config
foo: bar

---
# plugins config
tools:
  - name: foo
    instanceID: default
    options:
      fkk: [[ foo ]]
```

### Please read the documents below.

- [X] I've read the document [Creating a Documentation for DevStream](https://docs.devstream.io/en/latest/development/mkdocs/) and [Document Translation(Chinese only)](https://docs.devstream.io/en/latest/development/translation.zh/). (If you want to submit a document type contribution.)
