### ISSUE TITLE
:bomb: `Bug`: Harbor Can't be Logged In with Default Account

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#942]
### What Happened?

![image](https://user-images.githubusercontent.com/18692628/182840842-a95844a4-04fa-4071-abe9-10b13a9c7171.png)

### 1. Fill the `harbor.yaml` with:

```yaml
---
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state

---
tools:
# name of the tool
- name: harbor
  # id of the tool instance
  instanceID: default
  # format: name.instanceID; If specified, dtm will make sure the dependency is applied first before handling this tool.
  dependsOn: [ ]
  # options for the plugin
  options:
    create_namespace: true
    repo:
      name: harbor
      # url of the Helm repo, use self host helm config beacuse official helm does'nt support namespace config
      url: https://helm.goharbor.io
    # Helm chart information
    chart:
      # name of the chart
      chart_name: harbor/harbor
      # k8s namespace where Harbor will be installed
      namespace: harbor
      # release name of the chart
      release_name: harbor
      # whether to wait for the release to be deployed or not
      wait: true
      # the time to wait for any individual Kubernetes operation (like Jobs for hooks). This defaults to 5m0s
      timeout: 10m
      # whether to perform a CRD upgrade during installation
      upgradeCRDs: true
      values_yaml: |
        expose:
          type: nodePort
          tls:
            enabled: false
        chartmuseum:
          enabled: false
        clair:
          enabled: false
        notary:
          enabled: false
        trivy:
          enabled: false
```

### Anything else

N/A

### DevStream Version

latest
