### ISSUE TITLE
:bomb: `Bug`(artifactory):  The NodePort Configuration Injection is Failed

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#944]
### What Happened?

Apply `artifactory` plugin, Customized NodePort cannot be found.

![image](https://user-images.githubusercontent.com/18692628/182981732-076d50b9-e9d1-4077-ae67-bc62a9e65264.png)

The config file I was used:

```yaml
        values_yaml: |
          artifactory:
            service:
              type: NodePort
              nodePort: 30002
          nginx:
            enabled: false
```

- The complete configuration is as follows

```yaml
---
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state

---
tools:
  # name of the tool
  - name: artifactory
    # id of the tool instance
    instanceID: default
    # format: name.instanceID; If specified, dtm will make sure the dependency is applied first before handling this tool.
    dependsOn: [ ]
    # options for the plugin
    options:
      create_namespace: true
      repo:
        name: jfrog
        # url of the Helm repo, use self host helm config beacuse official helm does'nt support namespace config
        url: https://charts.jfrog.io
      # Helm chart information
      chart:
        # name of the chart
        chart_name: jfrog/artifactory
        # k8s namespace where Harbor will be installed
        namespace: artifactory
        # release name of the chart
        release_name: artifactory
        # whether to wait for the release to be deployed or not
        wait: true
        # the time to wait for any individual Kubernetes operation (like Jobs for hooks). This defaults to 5m0s
        timeout: 10m
        # whether to perform a CRD upgrade during installation
        upgradeCRDs: true
        values_yaml: |
          artifactory:
            service:
              type: NodePort
              nodePort: 30002
          nginx:
            enabled: false
```

### How to Reproduce?

1. Prepare the configuration file like above
2. Execute: `dtm apply xxx.yaml`

### Anything else

N/A

### DevStream Version

latest
