### ISSUE TITLE
:four_leaf_clover: `Proposal`: New Config format for github/gitlab aciton

### ISSUE THREAD

**Issue by steinliber** [devstream-io/devstream#952]
## What Would You Like to Add? Why Is This Needed?
Current `github action` and `gitlab ci` are all different, we can use a unified config for them。
```yaml
- name: githubactions-golang
  instanceID: default
  dependsOn: [ ]
  options:
    owner: YOUR_GITHUB_USERNAME
    org: YOUR_ORGANIZATION_NAME
    repo: YOUR_REPO_NAME
    language:
      name: go
      version: "1.18"
    branch: main
    build:
      enable: True
      command: "go build ./..."
    test:
      enable: True
      command: "go test ./..."
      coverage:
        enable: False
        profile: "-race -covermode=atomic"
        output: "coverage.out"
    docker:
      enable: True
      registry:
        type: dockerhub
        username: YOUR_DOCKERHUB_USERNAME
        repository: YOUR_DOCKERHUB_REPOSITORY
```
```yaml
  - name: gitlabci-golang
    # id of the tool instance
    instanceID: default
    # format: name.instanceID; If specified, dtm will make sure the dependency is applied first before handling this tool.
    dependsOn: [ ]
    # options for the plugin
    options:
      # owner/repo; "path with namespace" is only GitLab API's way of saying the same thing; please change the values below.
      pathWithNamespace: YOUR_GITLAB_USERNAME/YOUR_GITLAB_REPO_NAME
      # main branch of the repo (to which branch the plugin will submit the workflows)
      branch: main
```

## Design
we can use a unified config for them.
```yaml
- name: githubactions-golang
  instanceID: default
  dependsOn: [ ]
  options:
    repo:
      owner: YOUR_GITHUB_USERNAME
      org: YOUR_ORGANIZATION_NAME
      repo: YOUR_REPO_NAME
      branch: main
    ci:
      build:
        enable: True
      test:
        enable: True
        coverage:
          enable: True
    registry:
      type: dockerhub
      username: YOUR_DOCKERHUB_USERNAME
      repository: YOUR_DOCKERHUB_REPOSITORY
```
```yaml
- name: gitlabci-golang
  instanceID: default
  dependsOn: [ ]
  options:
    repo:
      owner: YOUR_GITLAB_USERNAME
      org: YOUR_ORGANIZATION_NAME
      repo: YOUR_REPO_NAME
      branch: main
    ci:
      build:
        enable: True
      test:
        enable: True
        coverage:
          enable: True
    registry:
      type: dockerhub
      username: YOUR_DOCKERHUB_USERNAME
      repository: YOUR_DOCKERHUB_REPOSITORY
```

**Comment by IronCore864** [comment]
## Min Config

I would like to propose a minimum possible config for users to get started ASAP, with many defaults:

```yaml
- name: githubactions-golang
  instanceID: default
  options:
    repoOwner: YOUR_GITHUB_USERNAME
    repoName: YOUR_REPO_NAME
```

Explanations:

- Build, and test is enabled by default; we can set "make build", "make test" as the default build/test command, so that it's compatible with all languages
- Test coverage (when possible) is also enabled by default
- Docker build/push is not enabled because the user didn't input docker-related options.

There are fewer indentations, so it's more readable and less likely to get wrong.
---

## Enable Docker Build/Push

If the user wants to enable docker build/push:

```yaml
- name: githubactions-golang
  instanceID: default
  options:
    repoOwner: YOUR_GITHUB_USERNAME
    repoName: YOUR_REPO_NAME
    imageRegistryType: dockerhub
    imageRegistry: YOUR_DOCKERHUB_USERNAME/YOUR_DOCKERHUB_REPOSITORY
```

Min config plus two settings.

If user wants to override 
```yaml
max config:
- name: githubactions-golang
  instanceID: default
  options:
    # repoOwner or org, must have one, and only one
    repoOwner: YOUR_GITHUB_USERNAME
    repoName: YOUR_REPO_NAME
    # build: defaults to `make build`
    buildCommand: some non-default command
    test:
      # defaults to `make test`
      command: some non-default test command
      # defaults to true
      coverage: false
    imageRegistryType: dockerhub
    imageRegistry: YOUR_DOCKERHUB_USERNAME/YOUR_DOCKERHUB_REPOSITORY
```
