### ISSUE TITLE
:four_leaf_clover: `Proposal`: Specify the Plugin Directory Through the Configuration file

### ISSUE THREAD

**Issue by daniel-hutao** [devstream-io/devstream#997]
## What Would You Like to Add? Why Is This Needed?

We have a `-d` flag to specify the plugin directory, and the default value is `.devstream`. I believe this flag doesn't play a value and almost everyone is using its default behavior.

I believe that using `dtm` in different directories is a very generic requirement, for example, if today I finish `init` in `/tmp` and tomorrow I run `dtm` again under `/root`, I want `dtm` to find the plugins I downloaded yesterday, not every time I tell `dtm` where the plugins are, or I can only run `dtm` in a specific directory.

## Design

1. delete `-d` flag;
2. add `pluginDir` in core config. e.g.

```yaml
# core config
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
pluginDir: "" If empty, use the "/usr/local/devstream/plugin" directory as default
state: # state config, backend can be local or s3
  backend: local
  options:
    stateFile: devstream.state
```

## Anything else

Done-Done Check

- [ ] All related documents and yaml files have been updated
- [ ] Feature has been implemented
- [ ] Feature has been tested and works properly
